# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0077a41bd172753fe46b7ebef8708af8d05ab06dab412b947ecb4e2e58b8af64af71482e724b4a4073200fe9e67f35fb5f1ac5fab240d7c9bf0fb070b41bacea

test:
  secret_key_base: 7c7a02c6fd6cf0b8687db2ce1a80791464f20c73091136c3faed0396cb9a8347cbec581ac18966f0a09f75c9beb37ea355b01fc0a544e35462a1fe68d4ce4875

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
